"""
M.A.I Tools — Supervisor Backup Manager
Backup & restore critical Supervisor config files to prevent token mismatch issues.
Place this file alongside the other mai_tools Python files.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import aiofiles
import voluptuous as vol
from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant
from aiohttp import web

SUPERVISOR_DATA_PATH = Path("/var/lib/homeassistant")
BACKUP_ROOT = Path("/config/.mai_supervisor_backups")

# Files that are critical for Supervisor to work correctly
CRITICAL_FILES = [
    "homeassistant.json",
    "config.json",
    "addons.json",
    "updater.json",
    "dns.json",
    "audio.json",
    "cli.json",
    "observer.json",
    "multicast.json",
    "ingress.json",
    "store.json",
    "discovery.json",
]

# Max number of backup snapshots to keep
MAX_SNAPSHOTS = 10

FIX_TOKEN_SCRIPT = """\
#!/bin/bash
# M.A.I Tools — Auto fix Supervisor token mismatch
# Generated by Supervisor Backup Manager

set -e

echo "[MAI] Reading correct token from Supervisor data..."
CORRECT_TOKEN=$(python3 -c "
import json
with open('/var/lib/homeassistant/homeassistant.json') as f:
    d = json.load(f)
print(d.get('access_token', ''))
")

if [ -z "$CORRECT_TOKEN" ]; then
    echo "[MAI] ERROR: Could not read access_token from homeassistant.json"
    exit 1
fi

echo "[MAI] Token found. Stopping homeassistant container..."
docker stop homeassistant 2>/dev/null || true
docker rm homeassistant 2>/dev/null || true

echo "[MAI] Recreating homeassistant container with correct token..."
docker run -d \\
  --name homeassistant \\
  --network=hassio \\
  -e SUPERVISOR=172.30.32.2 \\
  -e HASSIO=172.30.32.2 \\
  -e TZ=Asia/Ho_Chi_Minh \\
  -e SUPERVISOR_TOKEN=$CORRECT_TOKEN \\
  -e HASSIO_TOKEN=$CORRECT_TOKEN \\
  -e SUPERVISOR_CORE_API_SOCKET=/run/supervisor/core.sock \\
  -v /var/lib/homeassistant/homeassistant:/config \\
  -v /run/supervisor:/run/supervisor \\
  -p 8123:8123 \\
  --restart unless-stopped \\
  $(python3 -c "
import json
with open('/var/lib/homeassistant/homeassistant.json') as f:
    d = json.load(f)
print(d.get('image','ghcr.io/home-assistant/qemuarm-64-homeassistant') + ':' + d.get('version','latest'))
")

echo "[MAI] Done! Home Assistant restarted with correct token."
echo "[MAI] Wait 2-3 minutes for HA to fully start."
"""


def _get_snapshot_path(name: str) -> Path:
    return BACKUP_ROOT / name


def _list_snapshots() -> list[dict[str, Any]]:
    if not BACKUP_ROOT.exists():
        return []
    snapshots = []
    for d in sorted(BACKUP_ROOT.iterdir(), reverse=True):
        if not d.is_dir():
            continue
        meta_file = d / "meta.json"
        if meta_file.exists():
            try:
                with open(meta_file) as f:
                    meta = json.load(f)
                meta["id"] = d.name
                snapshots.append(meta)
            except Exception:
                pass
    return snapshots


def _do_backup(label: str = "") -> dict[str, Any]:
    """Create a snapshot of all critical Supervisor config files."""
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

    ts = datetime.now(timezone.utc)
    snapshot_id = ts.strftime("%Y%m%d_%H%M%S")
    snapshot_path = BACKUP_ROOT / snapshot_id
    snapshot_path.mkdir(parents=True, exist_ok=True)

    backed_up = []
    skipped = []

    for filename in CRITICAL_FILES:
        src = SUPERVISOR_DATA_PATH / filename
        if src.exists():
            shutil.copy2(src, snapshot_path / filename)
            backed_up.append(filename)
        else:
            skipped.append(filename)

    # Also read current token info for quick reference
    ha_json_path = snapshot_path / "homeassistant.json"
    token_info = {}
    if ha_json_path.exists():
        try:
            with open(ha_json_path) as f:
                ha_data = json.load(f)
            token_info = {
                "access_token_preview": ha_data.get("access_token", "")[:16] + "...",
                "ha_version": ha_data.get("version", "unknown"),
                "ha_image": ha_data.get("image", "unknown"),
            }
        except Exception:
            pass

    meta = {
        "snapshot_id": snapshot_id,
        "created_at": ts.isoformat(),
        "label": label or f"Auto backup {ts.strftime('%d/%m/%Y %H:%M')}",
        "files_backed_up": backed_up,
        "files_skipped": skipped,
        **token_info,
    }
    with open(snapshot_path / "meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    # Also write the fix-token script into the snapshot
    with open(snapshot_path / "fix_token.sh", "w") as f:
        f.write(FIX_TOKEN_SCRIPT)
    os.chmod(snapshot_path / "fix_token.sh", 0o755)

    # Prune old snapshots
    all_snapshots = sorted(BACKUP_ROOT.iterdir())
    while len(all_snapshots) > MAX_SNAPSHOTS:
        oldest = all_snapshots.pop(0)
        if oldest.is_dir():
            shutil.rmtree(oldest)

    return meta


def _do_restore(snapshot_id: str) -> dict[str, Any]:
    """Restore critical files from a snapshot (requires root / sudo)."""
    snapshot_path = BACKUP_ROOT / snapshot_id
    if not snapshot_path.exists():
        return {"success": False, "error": f"Snapshot {snapshot_id} not found"}

    restored = []
    errors = []

    for filename in CRITICAL_FILES:
        src = snapshot_path / filename
        if src.exists():
            dst = SUPERVISOR_DATA_PATH / filename
            try:
                shutil.copy2(src, dst)
                restored.append(filename)
            except PermissionError:
                # Try with sudo via subprocess
                result = subprocess.run(
                    ["sudo", "cp", str(src), str(dst)],
                    capture_output=True, text=True
                )
                if result.returncode == 0:
                    restored.append(filename)
                else:
                    errors.append(f"{filename}: {result.stderr.strip()}")

    return {
        "success": len(errors) == 0,
        "restored": restored,
        "errors": errors,
        "snapshot_id": snapshot_id,
        "note": "Restart hassio_supervisor + homeassistant containers to apply changes.",
    }


def _do_delete_snapshot(snapshot_id: str) -> bool:
    snapshot_path = BACKUP_ROOT / snapshot_id
    if snapshot_path.exists() and snapshot_path.is_dir():
        shutil.rmtree(snapshot_path)
        return True
    return False


def _get_current_status() -> dict[str, Any]:
    """Read current token and HA status for the UI."""
    status: dict[str, Any] = {
        "supervisor_data_accessible": SUPERVISOR_DATA_PATH.exists(),
        "ha_json_exists": (SUPERVISOR_DATA_PATH / "homeassistant.json").exists(),
        "current_token_preview": None,
        "ha_version": None,
        "ha_image": None,
        "docker_ha_token_preview": None,
        "token_mismatch": None,
    }

    # Read from file
    ha_json = SUPERVISOR_DATA_PATH / "homeassistant.json"
    if ha_json.exists():
        try:
            with open(ha_json) as f:
                d = json.load(f)
            file_token = d.get("access_token", "")
            status["current_token_preview"] = file_token[:16] + "..." if file_token else None
            status["ha_version"] = d.get("version")
            status["ha_image"] = d.get("image")
        except Exception as e:
            status["ha_json_error"] = str(e)

    # Try to get token from running docker container
    try:
        result = subprocess.run(
            ["docker", "exec", "homeassistant", "printenv", "SUPERVISOR_TOKEN"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            docker_token = result.stdout.strip()
            status["docker_ha_token_preview"] = docker_token[:16] + "..." if docker_token else None
            # Compare
            if status["current_token_preview"] and status["docker_ha_token_preview"]:
                file_token_full = ""
                if ha_json.exists():
                    with open(ha_json) as f:
                        file_token_full = json.load(f).get("access_token", "")
                status["token_mismatch"] = (docker_token != file_token_full)
    except Exception:
        status["docker_ha_token_preview"] = "N/A (cannot exec docker)"

    return status


# ─── HTTP API Views ──────────────────────────────────────────────────────────

class SupervisorBackupListView(HomeAssistantView):
    """GET /api/mai_tools/supervisor_backup/list"""
    url = "/api/mai_tools/supervisor_backup/list"
    name = "api:mai_tools:supervisor_backup:list"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        snapshots = await hass.async_add_executor_job(_list_snapshots)
        status = await hass.async_add_executor_job(_get_current_status)
        return self.json({"snapshots": snapshots, "status": status})


class SupervisorBackupCreateView(HomeAssistantView):
    """POST /api/mai_tools/supervisor_backup/create"""
    url = "/api/mai_tools/supervisor_backup/create"
    name = "api:mai_tools:supervisor_backup:create"
    requires_auth = True

    async def post(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        try:
            body = await request.json()
            label = body.get("label", "")
        except Exception:
            label = ""
        try:
            meta = await hass.async_add_executor_job(_do_backup, label)
            return self.json({"success": True, "snapshot": meta})
        except Exception as e:
            return self.json({"success": False, "error": str(e)}, status_code=500)


class SupervisorBackupRestoreView(HomeAssistantView):
    """POST /api/mai_tools/supervisor_backup/restore"""
    url = "/api/mai_tools/supervisor_backup/restore"
    name = "api:mai_tools:supervisor_backup:restore"
    requires_auth = True

    async def post(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        try:
            body = await request.json()
            snapshot_id = body.get("snapshot_id", "")
        except Exception:
            return self.json({"success": False, "error": "Missing snapshot_id"}, status_code=400)
        result = await hass.async_add_executor_job(_do_restore, snapshot_id)
        return self.json(result)


class SupervisorBackupDeleteView(HomeAssistantView):
    """DELETE /api/mai_tools/supervisor_backup/delete"""
    url = "/api/mai_tools/supervisor_backup/delete"
    name = "api:mai_tools:supervisor_backup:delete"
    requires_auth = True

    async def delete(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        try:
            body = await request.json()
            snapshot_id = body.get("snapshot_id", "")
        except Exception:
            return self.json({"success": False, "error": "Missing snapshot_id"}, status_code=400)
        ok = await hass.async_add_executor_job(_do_delete_snapshot, snapshot_id)
        return self.json({"success": ok})


class SupervisorBackupStatusView(HomeAssistantView):
    """GET /api/mai_tools/supervisor_backup/status"""
    url = "/api/mai_tools/supervisor_backup/status"
    name = "api:mai_tools:supervisor_backup:status"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        status = await hass.async_add_executor_job(_get_current_status)
        return self.json(status)


def register_views(hass: HomeAssistant) -> None:
    """Call this from your integration setup to register all views."""
    hass.http.register_view(SupervisorBackupListView)
    hass.http.register_view(SupervisorBackupCreateView)
    hass.http.register_view(SupervisorBackupRestoreView)
    hass.http.register_view(SupervisorBackupDeleteView)
    hass.http.register_view(SupervisorBackupStatusView)
